// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace AspDotNetStorefrontWSI.WSIEventSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AspDotNetStorefront WebService Event HandlerSoap", Namespace="http://www.aspdotnetstorefront.com/")]
    public partial class AspDotNetStorefrontWebServiceEventHandler : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSIAcceptEventReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AspDotNetStorefrontWebServiceEventHandler() {
            this.Url = global::AspDotNetStorefrontWSI.Properties.Settings.Default.AspDotNetStorefrontWSI_WSIEventSvc_AspDotNetStorefront_x0020_WebService_x0020_Event_x0020_Handler;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSIAcceptEventReportCompletedEventHandler WSIAcceptEventReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.aspdotnetstorefront.com/WSIAcceptEventReport", RequestNamespace="http://www.aspdotnetstorefront.com/", ResponseNamespace="http://www.aspdotnetstorefront.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSIAcceptEventReport(string EventType, string ReportingDomain, string EventXml) {
            object[] results = this.Invoke("WSIAcceptEventReport", new object[] {
                        EventType,
                        ReportingDomain,
                        EventXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSIAcceptEventReportAsync(string EventType, string ReportingDomain, string EventXml) {
            this.WSIAcceptEventReportAsync(EventType, ReportingDomain, EventXml, null);
        }
        
        /// <remarks/>
        public void WSIAcceptEventReportAsync(string EventType, string ReportingDomain, string EventXml, object userState) {
            if ((this.WSIAcceptEventReportOperationCompleted == null)) {
                this.WSIAcceptEventReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSIAcceptEventReportOperationCompleted);
            }
            this.InvokeAsync("WSIAcceptEventReport", new object[] {
                        EventType,
                        ReportingDomain,
                        EventXml}, this.WSIAcceptEventReportOperationCompleted, userState);
        }
        
        private void OnWSIAcceptEventReportOperationCompleted(object arg) {
            if ((this.WSIAcceptEventReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSIAcceptEventReportCompleted(this, new WSIAcceptEventReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSIAcceptEventReportCompletedEventHandler(object sender, WSIAcceptEventReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSIAcceptEventReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSIAcceptEventReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
