// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace AspDotNetStorefrontBuySafe.BuySafeWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BuySafeAPISoap", Namespace="http://ws.buysafe.com")]
    public partial class BuySafeAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MerchantServiceProviderCredentials merchantServiceProviderCredentialsValueField;
        
        private BuySafeWSHeader buySafeWSHeaderValueField;
        
        private TransactionStatus transactionStatusValueField;
        
        private System.Threading.SendOrPostCallback AddAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddStoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckEmailOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback PartnerRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailToReferrerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCharityListOptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmailOptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BuySafeAPI() {
            this.Url = global::AspDotNetStorefrontBuySafe.Properties.Settings.Default.AspDotNetStorefrontBuySafe_BuySafeWebReference_BuySafeAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MerchantServiceProviderCredentials MerchantServiceProviderCredentialsValue {
            get {
                return this.merchantServiceProviderCredentialsValueField;
            }
            set {
                this.merchantServiceProviderCredentialsValueField = value;
            }
        }
        
        public BuySafeWSHeader BuySafeWSHeaderValue {
            get {
                return this.buySafeWSHeaderValueField;
            }
            set {
                this.buySafeWSHeaderValueField = value;
            }
        }
        
        public TransactionStatus TransactionStatusValue {
            get {
                return this.transactionStatusValueField;
            }
            set {
                this.transactionStatusValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddAccountCompletedEventHandler AddAccountCompleted;
        
        /// <remarks/>
        public event AddStoreCompletedEventHandler AddStoreCompleted;
        
        /// <remarks/>
        public event CheckEmailOptionsCompletedEventHandler CheckEmailOptionsCompleted;
        
        /// <remarks/>
        public event GetAccountCompletedEventHandler GetAccountCompleted;
        
        /// <remarks/>
        public event PartnerRegistrationCompletedEventHandler PartnerRegistrationCompleted;
        
        /// <remarks/>
        public event SendEmailToReferrerCompletedEventHandler SendEmailToReferrerCompleted;
        
        /// <remarks/>
        public event UpdateCharityListOptionCompletedEventHandler UpdateCharityListOptionCompleted;
        
        /// <remarks/>
        public event UpdateEmailOptionCompletedEventHandler UpdateEmailOptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("MerchantServiceProviderCredentialsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/AddAccount", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddAccountRS")]
        public AddAccountRS AddAccount(AddAccountRQ AddAccountRQ) {
            object[] results = this.Invoke("AddAccount", new object[] {
                        AddAccountRQ});
            return ((AddAccountRS)(results[0]));
        }
        
        /// <remarks/>
        public void AddAccountAsync(AddAccountRQ AddAccountRQ) {
            this.AddAccountAsync(AddAccountRQ, null);
        }
        
        /// <remarks/>
        public void AddAccountAsync(AddAccountRQ AddAccountRQ, object userState) {
            if ((this.AddAccountOperationCompleted == null)) {
                this.AddAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAccountOperationCompleted);
            }
            this.InvokeAsync("AddAccount", new object[] {
                        AddAccountRQ}, this.AddAccountOperationCompleted, userState);
        }
        
        private void OnAddAccountOperationCompleted(object arg) {
            if ((this.AddAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAccountCompleted(this, new AddAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("MerchantServiceProviderCredentialsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/AddStore", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddStoreRS")]
        public AddStoreRS AddStore(AddStoreRQ AddStoreRQ) {
            object[] results = this.Invoke("AddStore", new object[] {
                        AddStoreRQ});
            return ((AddStoreRS)(results[0]));
        }
        
        /// <remarks/>
        public void AddStoreAsync(AddStoreRQ AddStoreRQ) {
            this.AddStoreAsync(AddStoreRQ, null);
        }
        
        /// <remarks/>
        public void AddStoreAsync(AddStoreRQ AddStoreRQ, object userState) {
            if ((this.AddStoreOperationCompleted == null)) {
                this.AddStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddStoreOperationCompleted);
            }
            this.InvokeAsync("AddStore", new object[] {
                        AddStoreRQ}, this.AddStoreOperationCompleted, userState);
        }
        
        private void OnAddStoreOperationCompleted(object arg) {
            if ((this.AddStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddStoreCompleted(this, new AddStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/CheckEmailOptions", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckEmailOptions(long BuySafeUser_Id) {
            object[] results = this.Invoke("CheckEmailOptions", new object[] {
                        BuySafeUser_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckEmailOptionsAsync(long BuySafeUser_Id) {
            this.CheckEmailOptionsAsync(BuySafeUser_Id, null);
        }
        
        /// <remarks/>
        public void CheckEmailOptionsAsync(long BuySafeUser_Id, object userState) {
            if ((this.CheckEmailOptionsOperationCompleted == null)) {
                this.CheckEmailOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckEmailOptionsOperationCompleted);
            }
            this.InvokeAsync("CheckEmailOptions", new object[] {
                        BuySafeUser_Id}, this.CheckEmailOptionsOperationCompleted, userState);
        }
        
        private void OnCheckEmailOptionsOperationCompleted(object arg) {
            if ((this.CheckEmailOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckEmailOptionsCompleted(this, new CheckEmailOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("MerchantServiceProviderCredentialsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/GetAccount", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAccountRS")]
        public GetAccountRS GetAccount(GetAccountRQ GetAccountRQ) {
            object[] results = this.Invoke("GetAccount", new object[] {
                        GetAccountRQ});
            return ((GetAccountRS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountAsync(GetAccountRQ GetAccountRQ) {
            this.GetAccountAsync(GetAccountRQ, null);
        }
        
        /// <remarks/>
        public void GetAccountAsync(GetAccountRQ GetAccountRQ, object userState) {
            if ((this.GetAccountOperationCompleted == null)) {
                this.GetAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountOperationCompleted);
            }
            this.InvokeAsync("GetAccount", new object[] {
                        GetAccountRQ}, this.GetAccountOperationCompleted, userState);
        }
        
        private void OnGetAccountOperationCompleted(object arg) {
            if ((this.GetAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountCompleted(this, new GetAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/PartnerRegistration", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PartnerRegistrationRS")]
        public PartnerRegistrationRS PartnerRegistration(PartnerRegistrationRQ PartnerRegistrationRQ) {
            object[] results = this.Invoke("PartnerRegistration", new object[] {
                        PartnerRegistrationRQ});
            return ((PartnerRegistrationRS)(results[0]));
        }
        
        /// <remarks/>
        public void PartnerRegistrationAsync(PartnerRegistrationRQ PartnerRegistrationRQ) {
            this.PartnerRegistrationAsync(PartnerRegistrationRQ, null);
        }
        
        /// <remarks/>
        public void PartnerRegistrationAsync(PartnerRegistrationRQ PartnerRegistrationRQ, object userState) {
            if ((this.PartnerRegistrationOperationCompleted == null)) {
                this.PartnerRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPartnerRegistrationOperationCompleted);
            }
            this.InvokeAsync("PartnerRegistration", new object[] {
                        PartnerRegistrationRQ}, this.PartnerRegistrationOperationCompleted, userState);
        }
        
        private void OnPartnerRegistrationOperationCompleted(object arg) {
            if ((this.PartnerRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PartnerRegistrationCompleted(this, new PartnerRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/SendEmailToReferrer", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendEmailToReferrer(string RefCode, long installerid) {
            object[] results = this.Invoke("SendEmailToReferrer", new object[] {
                        RefCode,
                        installerid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailToReferrerAsync(string RefCode, long installerid) {
            this.SendEmailToReferrerAsync(RefCode, installerid, null);
        }
        
        /// <remarks/>
        public void SendEmailToReferrerAsync(string RefCode, long installerid, object userState) {
            if ((this.SendEmailToReferrerOperationCompleted == null)) {
                this.SendEmailToReferrerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailToReferrerOperationCompleted);
            }
            this.InvokeAsync("SendEmailToReferrer", new object[] {
                        RefCode,
                        installerid}, this.SendEmailToReferrerOperationCompleted, userState);
        }
        
        private void OnSendEmailToReferrerOperationCompleted(object arg) {
            if ((this.SendEmailToReferrerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailToReferrerCompleted(this, new SendEmailToReferrerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/UpdateCharityListOption", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("InitialRewardsResultRS")]
        public InitialRewardsResultRS UpdateCharityListOption(string BuySafeUser_Id, string CharityOption, string PayPalEmailAddress) {
            object[] results = this.Invoke("UpdateCharityListOption", new object[] {
                        BuySafeUser_Id,
                        CharityOption,
                        PayPalEmailAddress});
            return ((InitialRewardsResultRS)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCharityListOptionAsync(string BuySafeUser_Id, string CharityOption, string PayPalEmailAddress) {
            this.UpdateCharityListOptionAsync(BuySafeUser_Id, CharityOption, PayPalEmailAddress, null);
        }
        
        /// <remarks/>
        public void UpdateCharityListOptionAsync(string BuySafeUser_Id, string CharityOption, string PayPalEmailAddress, object userState) {
            if ((this.UpdateCharityListOptionOperationCompleted == null)) {
                this.UpdateCharityListOptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCharityListOptionOperationCompleted);
            }
            this.InvokeAsync("UpdateCharityListOption", new object[] {
                        BuySafeUser_Id,
                        CharityOption,
                        PayPalEmailAddress}, this.UpdateCharityListOptionOperationCompleted, userState);
        }
        
        private void OnUpdateCharityListOptionOperationCompleted(object arg) {
            if ((this.UpdateCharityListOptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCharityListOptionCompleted(this, new UpdateCharityListOptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TransactionStatusValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("BuySafeWSHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.buysafe.com/UpdateEmailOption", RequestNamespace="http://ws.buysafe.com", ResponseNamespace="http://ws.buysafe.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateEmailOption(string BuySafeUser_Id, bool sendemail) {
            object[] results = this.Invoke("UpdateEmailOption", new object[] {
                        BuySafeUser_Id,
                        sendemail});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEmailOptionAsync(string BuySafeUser_Id, bool sendemail) {
            this.UpdateEmailOptionAsync(BuySafeUser_Id, sendemail, null);
        }
        
        /// <remarks/>
        public void UpdateEmailOptionAsync(string BuySafeUser_Id, bool sendemail, object userState) {
            if ((this.UpdateEmailOptionOperationCompleted == null)) {
                this.UpdateEmailOptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmailOptionOperationCompleted);
            }
            this.InvokeAsync("UpdateEmailOption", new object[] {
                        BuySafeUser_Id,
                        sendemail}, this.UpdateEmailOptionOperationCompleted, userState);
        }
        
        private void OnUpdateEmailOptionOperationCompleted(object arg) {
            if ((this.UpdateEmailOptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmailOptionCompleted(this, new UpdateEmailOptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.buysafe.com", IsNullable=false)]
    public partial class BuySafeWSHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string versionField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class InitialRewardsResultRS {
        
        private string initialResultFlagField;
        
        private string payPalEmailAddressField;
        
        /// <remarks/>
        public string InitialResultFlag {
            get {
                return this.initialResultFlagField;
            }
            set {
                this.initialResultFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PayPalEmailAddress {
            get {
                return this.payPalEmailAddressField;
            }
            set {
                this.payPalEmailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class PartnerRegistrationRQ {
        
        private string returnPassCodeField;
        
        private string handlerUrlField;
        
        private string partnerFieldField;
        
        private long mspIdField;
        
        private string invitationCodeField;
        
        private CountryCode workCountryField;
        
        private string workZipField;
        
        private string workStateFullField;
        
        private State workStateField;
        
        private string workCityField;
        
        private string workAddress2Field;
        
        private string workAddress1Field;
        
        private string homePhoneField;
        
        private string workPhoneField;
        
        private string emailField;
        
        private string storeUrlField;
        
        private string storeNameField;
        
        private Suffix suffixField;
        
        private string lastNameField;
        
        private string middleInitialField;
        
        private string firstNameField;
        
        private double averageMonthlySalesField;
        
        private System.DateTime dateBeganSellingField;
        
        private string companyNameField;
        
        private string faxField;
        
        /// <remarks/>
        public string ReturnPassCode {
            get {
                return this.returnPassCodeField;
            }
            set {
                this.returnPassCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HandlerUrl {
            get {
                return this.handlerUrlField;
            }
            set {
                this.handlerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string PartnerField {
            get {
                return this.partnerFieldField;
            }
            set {
                this.partnerFieldField = value;
            }
        }
        
        /// <remarks/>
        public long MspId {
            get {
                return this.mspIdField;
            }
            set {
                this.mspIdField = value;
            }
        }
        
        /// <remarks/>
        public string InvitationCode {
            get {
                return this.invitationCodeField;
            }
            set {
                this.invitationCodeField = value;
            }
        }
        
        /// <remarks/>
        public CountryCode WorkCountry {
            get {
                return this.workCountryField;
            }
            set {
                this.workCountryField = value;
            }
        }
        
        /// <remarks/>
        public string WorkZip {
            get {
                return this.workZipField;
            }
            set {
                this.workZipField = value;
            }
        }
        
        /// <remarks/>
        public string WorkStateFull {
            get {
                return this.workStateFullField;
            }
            set {
                this.workStateFullField = value;
            }
        }
        
        /// <remarks/>
        public State WorkState {
            get {
                return this.workStateField;
            }
            set {
                this.workStateField = value;
            }
        }
        
        /// <remarks/>
        public string WorkCity {
            get {
                return this.workCityField;
            }
            set {
                this.workCityField = value;
            }
        }
        
        /// <remarks/>
        public string WorkAddress2 {
            get {
                return this.workAddress2Field;
            }
            set {
                this.workAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string WorkAddress1 {
            get {
                return this.workAddress1Field;
            }
            set {
                this.workAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string StoreUrl {
            get {
                return this.storeUrlField;
            }
            set {
                this.storeUrlField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public Suffix Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public double AverageMonthlySales {
            get {
                return this.averageMonthlySalesField;
            }
            set {
                this.averageMonthlySalesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateBeganSelling {
            get {
                return this.dateBeganSellingField;
            }
            set {
                this.dateBeganSellingField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum CountryCode {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        OT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum State {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AK,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CT,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DC,
        
        /// <remarks/>
        FL,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        HI,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        IA,
        
        /// <remarks/>
        KS,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NV,
        
        /// <remarks/>
        NH,
        
        /// <remarks/>
        NJ,
        
        /// <remarks/>
        NM,
        
        /// <remarks/>
        NY,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        ND,
        
        /// <remarks/>
        OH,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RI,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TX,
        
        /// <remarks/>
        UT,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VT,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        WV,
        
        /// <remarks/>
        WI,
        
        /// <remarks/>
        WY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum Suffix {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Jr,
        
        /// <remarks/>
        Sr,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        II,
        
        /// <remarks/>
        III,
        
        /// <remarks/>
        IV,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VII,
        
        /// <remarks/>
        VIII,
        
        /// <remarks/>
        IX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class PartnerRegistrationRS {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class GetAccountRQ {
        
        private string accountHashField;
        
        private AccountSearch accountSearchField;
        
        /// <remarks/>
        public string AccountHash {
            get {
                return this.accountHashField;
            }
            set {
                this.accountHashField = value;
            }
        }
        
        /// <remarks/>
        public AccountSearch AccountSearch {
            get {
                return this.accountSearchField;
            }
            set {
                this.accountSearchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AccountSearch {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string companyNameField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class GetAccountRS {
        
        private AccountResponse accountResponseField;
        
        private StoreResponse[] storeResponseListField;
        
        private object errorInformationField;
        
        private AddUpdateSellerApplicationErrorType errorTypeField;
        
        private bool successfulField;
        
        /// <remarks/>
        public AccountResponse AccountResponse {
            get {
                return this.accountResponseField;
            }
            set {
                this.accountResponseField = value;
            }
        }
        
        /// <remarks/>
        public StoreResponse[] StoreResponseList {
            get {
                return this.storeResponseListField;
            }
            set {
                this.storeResponseListField = value;
            }
        }
        
        /// <remarks/>
        public object ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
        
        /// <remarks/>
        public AddUpdateSellerApplicationErrorType ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AccountResponse {
        
        private AccountResponseStatus statusField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string companyNameField;
        
        private string hashField;
        
        private string userNameField;
        
        /// <remarks/>
        public AccountResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum AccountResponseStatus {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Suspended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class StoreResponse {
        
        private MarketplaceResponseStatus statusField;
        
        private string userTokenField;
        
        private string nameField;
        
        private string urlField;
        
        private string emailField;
        
        private SubscriptionInformation subscriptionInformationField;
        
        /// <remarks/>
        public MarketplaceResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string UserToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionInformation SubscriptionInformation {
            get {
                return this.subscriptionInformationField;
            }
            set {
                this.subscriptionInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum MarketplaceResponseStatus {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Suspended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class SubscriptionInformation {
        
        private int termField;
        
        private string flatFeeField;
        
        private string transactionFeePercentField;
        
        private CustomDateTime beginDateField;
        
        /// <remarks/>
        public int Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string FlatFee {
            get {
                return this.flatFeeField;
            }
            set {
                this.flatFeeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionFeePercent {
            get {
                return this.transactionFeePercentField;
            }
            set {
                this.transactionFeePercentField = value;
            }
        }
        
        /// <remarks/>
        public CustomDateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class CustomDateTime {
        
        private System.DateTime dateTimeValueField;
        
        private bool hasDateTimeField;
        
        /// <remarks/>
        public System.DateTime DateTimeValue {
            get {
                return this.dateTimeValueField;
            }
            set {
                this.dateTimeValueField = value;
            }
        }
        
        /// <remarks/>
        public bool HasDateTime {
            get {
                return this.hasDateTimeField;
            }
            set {
                this.hasDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum AddUpdateSellerApplicationErrorType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        DupeEmail,
        
        /// <remarks/>
        DupeUserId,
        
        /// <remarks/>
        DupeSSN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AddStoreRQ {
        
        private string accountHashField;
        
        private StoreInformation[] addStoreListField;
        
        /// <remarks/>
        public string AccountHash {
            get {
                return this.accountHashField;
            }
            set {
                this.accountHashField = value;
            }
        }
        
        /// <remarks/>
        public StoreInformation[] AddStoreList {
            get {
                return this.addStoreListField;
            }
            set {
                this.addStoreListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class StoreInformation {
        
        private string nameField;
        
        private string urlField;
        
        private string emailField;
        
        private string checkOutUrlField;
        
        private string termsOfSaleField;
        
        private double storeMonthlyGMSField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CheckOutUrl {
            get {
                return this.checkOutUrlField;
            }
            set {
                this.checkOutUrlField = value;
            }
        }
        
        /// <remarks/>
        public string TermsOfSale {
            get {
                return this.termsOfSaleField;
            }
            set {
                this.termsOfSaleField = value;
            }
        }
        
        /// <remarks/>
        public double StoreMonthlyGMS {
            get {
                return this.storeMonthlyGMSField;
            }
            set {
                this.storeMonthlyGMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AddStoreRS {
        
        private StoreResponse[] storeResponseListField;
        
        private object errorInformationField;
        
        private AddUpdateSellerApplicationErrorType errorTypeField;
        
        private bool successfulField;
        
        /// <remarks/>
        public StoreResponse[] StoreResponseList {
            get {
                return this.storeResponseListField;
            }
            set {
                this.storeResponseListField = value;
            }
        }
        
        /// <remarks/>
        public object ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
        
        /// <remarks/>
        public AddUpdateSellerApplicationErrorType ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AddAccountRS {
        
        private AccountResponse accountResponseField;
        
        private StoreResponse[] storeResponseListField;
        
        private object errorInformationField;
        
        private AddUpdateSellerApplicationErrorType errorTypeField;
        
        private bool successfulField;
        
        /// <remarks/>
        public AccountResponse AccountResponse {
            get {
                return this.accountResponseField;
            }
            set {
                this.accountResponseField = value;
            }
        }
        
        /// <remarks/>
        public StoreResponse[] StoreResponseList {
            get {
                return this.storeResponseListField;
            }
            set {
                this.storeResponseListField = value;
            }
        }
        
        /// <remarks/>
        public object ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
        
        /// <remarks/>
        public AddUpdateSellerApplicationErrorType ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class CreditCard {
        
        private long paymentProfileIDField;
        
        private long addressIDField;
        
        private CreditCardType typeField;
        
        private string nameOnCardField;
        
        private CustomDateTime expirationDateField;
        
        private string numberField;
        
        private string securityCodeField;
        
        /// <remarks/>
        public long PaymentProfileID {
            get {
                return this.paymentProfileIDField;
            }
            set {
                this.paymentProfileIDField = value;
            }
        }
        
        /// <remarks/>
        public long AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        public CustomDateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum CreditCardType {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Visa,
        
        /// <remarks/>
        Mastercard,
        
        /// <remarks/>
        AmericanExpress,
        
        /// <remarks/>
        Discover,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class PaymentInformation {
        
        private CreditCard creditCardField;
        
        /// <remarks/>
        public CreditCard CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class LoginInformation {
        
        private string userNameField;
        
        private bool autoGenerateOnCollisionField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoGenerateOnCollision {
            get {
                return this.autoGenerateOnCollisionField;
            }
            set {
                this.autoGenerateOnCollisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class Phone {
        
        private string numberField;
        
        private string extensionField;
        
        private PhoneType typeField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum PhoneType {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        Cell,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Truste,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class Address {
        
        private string streetLine1Field;
        
        private string streetLine2Field;
        
        private string cityNameField;
        
        private string stateProvinceField;
        
        private AddressType typeField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private CountryCode countryCodeField;
        
        /// <remarks/>
        public string StreetLine1 {
            get {
                return this.streetLine1Field;
            }
            set {
                this.streetLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string StreetLine2 {
            get {
                return this.streetLine2Field;
            }
            set {
                this.streetLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public CountryCode CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public enum AddressType {
        
        /// <remarks/>
        DoesNotApply,
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        PreviousHome,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        DriversLicense,
        
        /// <remarks/>
        CreditCard,
        
        /// <remarks/>
        Truste,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class BusinessInformation {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string titleField;
        
        private bool isPrimaryOwnerField;
        
        private string suffixField;
        
        private string middleInitialField;
        
        private string companyNameField;
        
        private double averageMonthlyGrossSalesField;
        
        private string promoCodeField;
        
        private Address addressField;
        
        private Phone phoneField;
        
        private CustomDateTime dateBeganSellingField;
        
        private bool allowPartnerContactField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public bool isPrimaryOwner {
            get {
                return this.isPrimaryOwnerField;
            }
            set {
                this.isPrimaryOwnerField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public double AverageMonthlyGrossSales {
            get {
                return this.averageMonthlyGrossSalesField;
            }
            set {
                this.averageMonthlyGrossSalesField = value;
            }
        }
        
        /// <remarks/>
        public string PromoCode {
            get {
                return this.promoCodeField;
            }
            set {
                this.promoCodeField = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public Phone Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public CustomDateTime DateBeganSelling {
            get {
                return this.dateBeganSellingField;
            }
            set {
                this.dateBeganSellingField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowPartnerContact {
            get {
                return this.allowPartnerContactField;
            }
            set {
                this.allowPartnerContactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AddAccountRQ {
        
        private BusinessInformation businessInformationField;
        
        private LoginInformation loginInformationField;
        
        private StoreInformation[] addStoreListField;
        
        private PaymentInformation paymentInformationField;
        
        /// <remarks/>
        public BusinessInformation BusinessInformation {
            get {
                return this.businessInformationField;
            }
            set {
                this.businessInformationField = value;
            }
        }
        
        /// <remarks/>
        public LoginInformation LoginInformation {
            get {
                return this.loginInformationField;
            }
            set {
                this.loginInformationField = value;
            }
        }
        
        /// <remarks/>
        public StoreInformation[] AddStoreList {
            get {
                return this.addStoreListField;
            }
            set {
                this.addStoreListField = value;
            }
        }
        
        /// <remarks/>
        public PaymentInformation PaymentInformation {
            get {
                return this.paymentInformationField;
            }
            set {
                this.paymentInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    public partial class AdvisoryInfo {
        
        private bool isFatalField;
        
        private string errorCauseField;
        
        private string errorSolutionField;
        
        /// <remarks/>
        public bool isFatal {
            get {
                return this.isFatalField;
            }
            set {
                this.isFatalField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCause {
            get {
                return this.errorCauseField;
            }
            set {
                this.errorCauseField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorSolution {
            get {
                return this.errorSolutionField;
            }
            set {
                this.errorSolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.buysafe.com", IsNullable=false)]
    public partial class MerchantServiceProviderCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.buysafe.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.buysafe.com", IsNullable=false)]
    public partial class TransactionStatus : System.Web.Services.Protocols.SoapHeader {
        
        private long transactionIdField;
        
        private bool isSuccessfulField;
        
        private AdvisoryInfo[] advisoryListField;
        
        /// <remarks/>
        public long TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public AdvisoryInfo[] AdvisoryList {
            get {
                return this.advisoryListField;
            }
            set {
                this.advisoryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddAccountCompletedEventHandler(object sender, AddAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddAccountRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddAccountRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddStoreCompletedEventHandler(object sender, AddStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddStoreRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddStoreRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckEmailOptionsCompletedEventHandler(object sender, CheckEmailOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckEmailOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckEmailOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAccountCompletedEventHandler(object sender, GetAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAccountRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAccountRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PartnerRegistrationCompletedEventHandler(object sender, PartnerRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartnerRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PartnerRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PartnerRegistrationRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PartnerRegistrationRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendEmailToReferrerCompletedEventHandler(object sender, SendEmailToReferrerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailToReferrerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailToReferrerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateCharityListOptionCompletedEventHandler(object sender, UpdateCharityListOptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCharityListOptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCharityListOptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitialRewardsResultRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitialRewardsResultRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateEmailOptionCompletedEventHandler(object sender, UpdateEmailOptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEmailOptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEmailOptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
