// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetStorefrontGateways.MaxMind {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MINFRAUD", Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap")]
    [System.SerializableAttribute()]
    public partial class MINFRAUD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anonymousProxyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binNameMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binPhoneMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carderEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityPostalMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custPhoneInBillingLocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string freeMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string highRiskCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string highRiskPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string highRiskUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_accuracyRadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_areaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_asnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_cityConfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_continentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_corporateProxyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_countryConfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_countryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_domainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_ispField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_metroCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_netSpeedCellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_orgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_postalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_postalConfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_regionConfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_regionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_timeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_userTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isTransProxyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maxmindIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string minfraud_versionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prepaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proxyScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queriesRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string riskScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCityPostalMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipForwardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string anonymousProxy {
            get {
                return this.anonymousProxyField;
            }
            set {
                if ((object.ReferenceEquals(this.anonymousProxyField, value) != true)) {
                    this.anonymousProxyField = value;
                    this.RaisePropertyChanged("anonymousProxy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binCountry {
            get {
                return this.binCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.binCountryField, value) != true)) {
                    this.binCountryField = value;
                    this.RaisePropertyChanged("binCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binMatch {
            get {
                return this.binMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.binMatchField, value) != true)) {
                    this.binMatchField = value;
                    this.RaisePropertyChanged("binMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binName {
            get {
                return this.binNameField;
            }
            set {
                if ((object.ReferenceEquals(this.binNameField, value) != true)) {
                    this.binNameField = value;
                    this.RaisePropertyChanged("binName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binNameMatch {
            get {
                return this.binNameMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.binNameMatchField, value) != true)) {
                    this.binNameMatchField = value;
                    this.RaisePropertyChanged("binNameMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binPhone {
            get {
                return this.binPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.binPhoneField, value) != true)) {
                    this.binPhoneField = value;
                    this.RaisePropertyChanged("binPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string binPhoneMatch {
            get {
                return this.binPhoneMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.binPhoneMatchField, value) != true)) {
                    this.binPhoneMatchField = value;
                    this.RaisePropertyChanged("binPhoneMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carderEmail {
            get {
                return this.carderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.carderEmailField, value) != true)) {
                    this.carderEmailField = value;
                    this.RaisePropertyChanged("carderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cityPostalMatch {
            get {
                return this.cityPostalMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.cityPostalMatchField, value) != true)) {
                    this.cityPostalMatchField = value;
                    this.RaisePropertyChanged("cityPostalMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countryCodeField, value) != true)) {
                    this.countryCodeField = value;
                    this.RaisePropertyChanged("countryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string countryMatch {
            get {
                return this.countryMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.countryMatchField, value) != true)) {
                    this.countryMatchField = value;
                    this.RaisePropertyChanged("countryMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string custPhoneInBillingLoc {
            get {
                return this.custPhoneInBillingLocField;
            }
            set {
                if ((object.ReferenceEquals(this.custPhoneInBillingLocField, value) != true)) {
                    this.custPhoneInBillingLocField = value;
                    this.RaisePropertyChanged("custPhoneInBillingLoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                if ((object.ReferenceEquals(this.distanceField, value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string err {
            get {
                return this.errField;
            }
            set {
                if ((object.ReferenceEquals(this.errField, value) != true)) {
                    this.errField = value;
                    this.RaisePropertyChanged("err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string freeMail {
            get {
                return this.freeMailField;
            }
            set {
                if ((object.ReferenceEquals(this.freeMailField, value) != true)) {
                    this.freeMailField = value;
                    this.RaisePropertyChanged("freeMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string highRiskCountry {
            get {
                return this.highRiskCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.highRiskCountryField, value) != true)) {
                    this.highRiskCountryField = value;
                    this.RaisePropertyChanged("highRiskCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string highRiskPassword {
            get {
                return this.highRiskPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.highRiskPasswordField, value) != true)) {
                    this.highRiskPasswordField = value;
                    this.RaisePropertyChanged("highRiskPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string highRiskUsername {
            get {
                return this.highRiskUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.highRiskUsernameField, value) != true)) {
                    this.highRiskUsernameField = value;
                    this.RaisePropertyChanged("highRiskUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_accuracyRadius {
            get {
                return this.ip_accuracyRadiusField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_accuracyRadiusField, value) != true)) {
                    this.ip_accuracyRadiusField = value;
                    this.RaisePropertyChanged("ip_accuracyRadius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_areaCode {
            get {
                return this.ip_areaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_areaCodeField, value) != true)) {
                    this.ip_areaCodeField = value;
                    this.RaisePropertyChanged("ip_areaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_asnum {
            get {
                return this.ip_asnumField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_asnumField, value) != true)) {
                    this.ip_asnumField = value;
                    this.RaisePropertyChanged("ip_asnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_city {
            get {
                return this.ip_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_cityField, value) != true)) {
                    this.ip_cityField = value;
                    this.RaisePropertyChanged("ip_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_cityConf {
            get {
                return this.ip_cityConfField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_cityConfField, value) != true)) {
                    this.ip_cityConfField = value;
                    this.RaisePropertyChanged("ip_cityConf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_continentCode {
            get {
                return this.ip_continentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_continentCodeField, value) != true)) {
                    this.ip_continentCodeField = value;
                    this.RaisePropertyChanged("ip_continentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_corporateProxy {
            get {
                return this.ip_corporateProxyField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_corporateProxyField, value) != true)) {
                    this.ip_corporateProxyField = value;
                    this.RaisePropertyChanged("ip_corporateProxy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_countryConf {
            get {
                return this.ip_countryConfField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_countryConfField, value) != true)) {
                    this.ip_countryConfField = value;
                    this.RaisePropertyChanged("ip_countryConf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_countryName {
            get {
                return this.ip_countryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_countryNameField, value) != true)) {
                    this.ip_countryNameField = value;
                    this.RaisePropertyChanged("ip_countryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_domain {
            get {
                return this.ip_domainField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_domainField, value) != true)) {
                    this.ip_domainField = value;
                    this.RaisePropertyChanged("ip_domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_isp {
            get {
                return this.ip_ispField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_ispField, value) != true)) {
                    this.ip_ispField = value;
                    this.RaisePropertyChanged("ip_isp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_latitude {
            get {
                return this.ip_latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_latitudeField, value) != true)) {
                    this.ip_latitudeField = value;
                    this.RaisePropertyChanged("ip_latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_longitude {
            get {
                return this.ip_longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_longitudeField, value) != true)) {
                    this.ip_longitudeField = value;
                    this.RaisePropertyChanged("ip_longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_metroCode {
            get {
                return this.ip_metroCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_metroCodeField, value) != true)) {
                    this.ip_metroCodeField = value;
                    this.RaisePropertyChanged("ip_metroCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_netSpeedCell {
            get {
                return this.ip_netSpeedCellField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_netSpeedCellField, value) != true)) {
                    this.ip_netSpeedCellField = value;
                    this.RaisePropertyChanged("ip_netSpeedCell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_org {
            get {
                return this.ip_orgField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_orgField, value) != true)) {
                    this.ip_orgField = value;
                    this.RaisePropertyChanged("ip_org");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_postalCode {
            get {
                return this.ip_postalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_postalCodeField, value) != true)) {
                    this.ip_postalCodeField = value;
                    this.RaisePropertyChanged("ip_postalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_postalConf {
            get {
                return this.ip_postalConfField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_postalConfField, value) != true)) {
                    this.ip_postalConfField = value;
                    this.RaisePropertyChanged("ip_postalConf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_region {
            get {
                return this.ip_regionField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_regionField, value) != true)) {
                    this.ip_regionField = value;
                    this.RaisePropertyChanged("ip_region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_regionConf {
            get {
                return this.ip_regionConfField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_regionConfField, value) != true)) {
                    this.ip_regionConfField = value;
                    this.RaisePropertyChanged("ip_regionConf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_regionName {
            get {
                return this.ip_regionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_regionNameField, value) != true)) {
                    this.ip_regionNameField = value;
                    this.RaisePropertyChanged("ip_regionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_timeZone {
            get {
                return this.ip_timeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_timeZoneField, value) != true)) {
                    this.ip_timeZoneField = value;
                    this.RaisePropertyChanged("ip_timeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ip_userType {
            get {
                return this.ip_userTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_userTypeField, value) != true)) {
                    this.ip_userTypeField = value;
                    this.RaisePropertyChanged("ip_userType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string isTransProxy {
            get {
                return this.isTransProxyField;
            }
            set {
                if ((object.ReferenceEquals(this.isTransProxyField, value) != true)) {
                    this.isTransProxyField = value;
                    this.RaisePropertyChanged("isTransProxy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string maxmindID {
            get {
                return this.maxmindIDField;
            }
            set {
                if ((object.ReferenceEquals(this.maxmindIDField, value) != true)) {
                    this.maxmindIDField = value;
                    this.RaisePropertyChanged("maxmindID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string minfraud_version {
            get {
                return this.minfraud_versionField;
            }
            set {
                if ((object.ReferenceEquals(this.minfraud_versionField, value) != true)) {
                    this.minfraud_versionField = value;
                    this.RaisePropertyChanged("minfraud_version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prepaid {
            get {
                return this.prepaidField;
            }
            set {
                if ((object.ReferenceEquals(this.prepaidField, value) != true)) {
                    this.prepaidField = value;
                    this.RaisePropertyChanged("prepaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string proxyScore {
            get {
                return this.proxyScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.proxyScoreField, value) != true)) {
                    this.proxyScoreField = value;
                    this.RaisePropertyChanged("proxyScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string queriesRemaining {
            get {
                return this.queriesRemainingField;
            }
            set {
                if ((object.ReferenceEquals(this.queriesRemainingField, value) != true)) {
                    this.queriesRemainingField = value;
                    this.RaisePropertyChanged("queriesRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string riskScore {
            get {
                return this.riskScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.riskScoreField, value) != true)) {
                    this.riskScoreField = value;
                    this.RaisePropertyChanged("riskScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string service_level {
            get {
                return this.service_levelField;
            }
            set {
                if ((object.ReferenceEquals(this.service_levelField, value) != true)) {
                    this.service_levelField = value;
                    this.RaisePropertyChanged("service_level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string shipCityPostalMatch {
            get {
                return this.shipCityPostalMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCityPostalMatchField, value) != true)) {
                    this.shipCityPostalMatchField = value;
                    this.RaisePropertyChanged("shipCityPostalMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string shipForward {
            get {
                return this.shipForwardField;
            }
            set {
                if ((object.ReferenceEquals(this.shipForwardField, value) != true)) {
                    this.shipForwardField = value;
                    this.RaisePropertyChanged("shipForward");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap", ConfigurationName="MaxMind.minfraudWebServiceSoap")]
    public interface minfraudWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name accept_language from namespace http://www.maxmind.com/maxmind_soap/minfraud_soap is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.maxmind.com/maxmind_soap/minfraud_soap#minfraud_soap14", ReplyAction="*")]
        AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Response minfraud_soap14(AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minfraud_soap14Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minfraud_soap14", Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap", Order=0)]
        public AspDotNetStorefrontGateways.MaxMind.minfraud_soap14RequestBody Body;
        
        public minfraud_soap14Request() {
        }
        
        public minfraud_soap14Request(AspDotNetStorefrontGateways.MaxMind.minfraud_soap14RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap")]
    public partial class minfraud_soap14RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accept_language;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string i;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string postal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string bin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string binName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string binPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string custPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string license_key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string requested_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string forwardedIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string emailMD5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string usernameMD5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string passwordMD5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string shipAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string shipCity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string shipRegion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string shipPostal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string shipCountry;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string txnID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string user_agent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string order_amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string order_currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string shopID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string avs_result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string cvv_result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string txn_type;
        
        public minfraud_soap14RequestBody() {
        }
        
        public minfraud_soap14RequestBody(
                    string accept_language, 
                    string i, 
                    string city, 
                    string region, 
                    string postal, 
                    string country, 
                    string domain, 
                    string bin, 
                    string binName, 
                    string binPhone, 
                    string custPhone, 
                    string license_key, 
                    string requested_type, 
                    string forwardedIP, 
                    string emailMD5, 
                    string usernameMD5, 
                    string passwordMD5, 
                    string shipAddr, 
                    string shipCity, 
                    string shipRegion, 
                    string shipPostal, 
                    string shipCountry, 
                    string txnID, 
                    string sessionID, 
                    string user_agent, 
                    string order_amount, 
                    string order_currency, 
                    string shopID, 
                    string avs_result, 
                    string cvv_result, 
                    string txn_type) {
            this.accept_language = accept_language;
            this.i = i;
            this.city = city;
            this.region = region;
            this.postal = postal;
            this.country = country;
            this.domain = domain;
            this.bin = bin;
            this.binName = binName;
            this.binPhone = binPhone;
            this.custPhone = custPhone;
            this.license_key = license_key;
            this.requested_type = requested_type;
            this.forwardedIP = forwardedIP;
            this.emailMD5 = emailMD5;
            this.usernameMD5 = usernameMD5;
            this.passwordMD5 = passwordMD5;
            this.shipAddr = shipAddr;
            this.shipCity = shipCity;
            this.shipRegion = shipRegion;
            this.shipPostal = shipPostal;
            this.shipCountry = shipCountry;
            this.txnID = txnID;
            this.sessionID = sessionID;
            this.user_agent = user_agent;
            this.order_amount = order_amount;
            this.order_currency = order_currency;
            this.shopID = shopID;
            this.avs_result = avs_result;
            this.cvv_result = cvv_result;
            this.txn_type = txn_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minfraud_soap14Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minfraud_soap14Response", Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap", Order=0)]
        public AspDotNetStorefrontGateways.MaxMind.minfraud_soap14ResponseBody Body;
        
        public minfraud_soap14Response() {
        }
        
        public minfraud_soap14Response(AspDotNetStorefrontGateways.MaxMind.minfraud_soap14ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.maxmind.com/maxmind_soap/minfraud_soap")]
    public partial class minfraud_soap14ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AspDotNetStorefrontGateways.MaxMind.MINFRAUD minfraud_output;
        
        public minfraud_soap14ResponseBody() {
        }
        
        public minfraud_soap14ResponseBody(AspDotNetStorefrontGateways.MaxMind.MINFRAUD minfraud_output) {
            this.minfraud_output = minfraud_output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface minfraudWebServiceSoapChannel : AspDotNetStorefrontGateways.MaxMind.minfraudWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class minfraudWebServiceSoapClient : System.ServiceModel.ClientBase<AspDotNetStorefrontGateways.MaxMind.minfraudWebServiceSoap>, AspDotNetStorefrontGateways.MaxMind.minfraudWebServiceSoap {
        
        public minfraudWebServiceSoapClient() {
        }
        
        public minfraudWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public minfraudWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public minfraudWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public minfraudWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Response AspDotNetStorefrontGateways.MaxMind.minfraudWebServiceSoap.minfraud_soap14(AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Request request) {
            return base.Channel.minfraud_soap14(request);
        }
        
        public AspDotNetStorefrontGateways.MaxMind.MINFRAUD minfraud_soap14(
                    string accept_language, 
                    string i, 
                    string city, 
                    string region, 
                    string postal, 
                    string country, 
                    string domain, 
                    string bin, 
                    string binName, 
                    string binPhone, 
                    string custPhone, 
                    string license_key, 
                    string requested_type, 
                    string forwardedIP, 
                    string emailMD5, 
                    string usernameMD5, 
                    string passwordMD5, 
                    string shipAddr, 
                    string shipCity, 
                    string shipRegion, 
                    string shipPostal, 
                    string shipCountry, 
                    string txnID, 
                    string sessionID, 
                    string user_agent, 
                    string order_amount, 
                    string order_currency, 
                    string shopID, 
                    string avs_result, 
                    string cvv_result, 
                    string txn_type) {
            AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Request inValue = new AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Request();
            inValue.Body = new AspDotNetStorefrontGateways.MaxMind.minfraud_soap14RequestBody();
            inValue.Body.accept_language = accept_language;
            inValue.Body.i = i;
            inValue.Body.city = city;
            inValue.Body.region = region;
            inValue.Body.postal = postal;
            inValue.Body.country = country;
            inValue.Body.domain = domain;
            inValue.Body.bin = bin;
            inValue.Body.binName = binName;
            inValue.Body.binPhone = binPhone;
            inValue.Body.custPhone = custPhone;
            inValue.Body.license_key = license_key;
            inValue.Body.requested_type = requested_type;
            inValue.Body.forwardedIP = forwardedIP;
            inValue.Body.emailMD5 = emailMD5;
            inValue.Body.usernameMD5 = usernameMD5;
            inValue.Body.passwordMD5 = passwordMD5;
            inValue.Body.shipAddr = shipAddr;
            inValue.Body.shipCity = shipCity;
            inValue.Body.shipRegion = shipRegion;
            inValue.Body.shipPostal = shipPostal;
            inValue.Body.shipCountry = shipCountry;
            inValue.Body.txnID = txnID;
            inValue.Body.sessionID = sessionID;
            inValue.Body.user_agent = user_agent;
            inValue.Body.order_amount = order_amount;
            inValue.Body.order_currency = order_currency;
            inValue.Body.shopID = shopID;
            inValue.Body.avs_result = avs_result;
            inValue.Body.cvv_result = cvv_result;
            inValue.Body.txn_type = txn_type;
            AspDotNetStorefrontGateways.MaxMind.minfraud_soap14Response retVal = ((AspDotNetStorefrontGateways.MaxMind.minfraudWebServiceSoap)(this)).minfraud_soap14(inValue);
            return retVal.Body.minfraud_output;
        }
    }
}
